Update registration_runbook.md
devopsdays-austin/runbooks pull request #15
Opened 2023-12-13 05:39 UTC by a4orce84

Updating runbook with 2023 lessons learned and updates.

2023-12-13 05:41 UTC, a4orce84 reviewed
Made updates to registration runbook with lessons learned from 2023.

2023-12-13 20:07 UTC, nimbinatus requested changes
Couple small changes, but this is a great start! Lmk when you address these comments and suggestions, and I'll merge it.

2023-12-13 20:07 UTC, nimbinatus commented on registration_runbook.md
```suggestion
```
This line was boilerplate :)

2023-12-13 20:07 UTC, nimbinatus commented on registration_runbook.md
> +* Work with Website Organizer Team to coordinate when we should promote ticket sales (Early Bird, Normal Sale, etc.).
Dates (the when) is a core question, but you are coordinating with website to get the links up

2023-12-13 20:07 UTC, nimbinatus commented on registration_runbook.md
> +* Work with Swag Organizer Team to ensure we have enough t-shirts for the total number of attendees.
```suggestion
* Work with Swag Organizer Team to ensure we have enough t-shirts, lanyards, and badges for the total number of attendees.
```

2023-12-13 20:07 UTC, nimbinatus commented on registration_runbook.md
> +**Important Note: Prior to 2024 we used Eventbrite (2024 will be the first year we are using X tool), so keep in mind some of the common mistakes may be framed around using the Eventbrite tool.**
```suggestion
**Important Note: Prior to 2024 we used Eventbrite (2024 will be the first year we are using the Pretix tool), so keep in mind some of the common mistakes may be framed around using the Eventbrite tool.**
```

2023-12-19 05:00 UTC, moutons commented
Great start! I would like to see more information about prep-day and day-of responsibilities, broken down between what the Organizers and Volunteers who are doing this work are responsible for. It doesn't necessarily need to be an explicit list of every individual task that needs to happen during the conference, but it would be good to note what the group is responsible for in order to pull off the conference smoothly ("don't forget this" sort of stuff) and where teams need to work together, for example:

Prior to the conference:
- On prep day, set up registration tables, daily swag, badges, and related equipment (Registration Orgs, Volunteers, Swag Orgs)
- On prep day, make sure badges are easily distributed as people register

During the conference:
- Distribute shirts and daily swag as people register (Volunteers)

Thanks

2024-05-08 20:08 UTC, moutons commented on registration_runbook.md
> +* Work with Website Organizer Team to coordinate when we should promote ticket sales (Early Bird, Normal Sale, etc.).
```suggestion
* Work with Website and Core Organizer Team to coordinate when we should promote ticket sales (Early Bird, Normal Sale, etc.).
```

2024-05-08 20:21 UTC, nimbinatus approved these changes
approving knowing #20 is out there

2024-05-08 20:21 UTC, merged